import { db } from "./db";
import { installers } from "@shared/schema";

const seedData = [
  // =================== UP TO 500 KW (public bucket) ===================
  {
    nameAr: "اس ايه اس لحلول الطاقة الذكية",
    nameEn: "SES – Sustainable Energy Solutions",
    sourceCategory: "up_to_50kw",
    publicCategory: "up_to_500kw",
    stationsCount: 32,
    installedPowerKw: 754.30,
    installedPowerDisplay: "754 kW",
    phone: "+20 127 015 0222",
    email: "A.haridi@sesolu.com",
    website: "https://www.ses.com.eg",
    facebookUrl: "",
    location: "Cairo",
    descriptionAr: "شركة متخصصة في حلول الطاقة الذكية والمستدامة، تقدم خدمات EPC وO&M لمشاريع الطاقة الشمسية والمتجددة منذ 2008.",
    descriptionEn: "Specialist in smart and sustainable energy solutions, providing EPC and O&M services for solar and renewable energy projects since 2008.",
    featured: true,
    hidden: false,
  },
  {
    nameAr: "ار اى اس للطاقة المتجددة",
    nameEn: "R.E.S for Renewable Energy",
    sourceCategory: "up_to_50kw",
    publicCategory: "up_to_500kw",
    stationsCount: 1,
    installedPowerKw: 20.00,
    installedPowerDisplay: "20 kW",
    phone: "+20 100 558 6817",
    email: "abdelrahman.attaa@gmail.com",
    website: "",
    facebookUrl: "https://www.facebook.com/61585631332009/",
    location: "Bani Mazar, Al Minya",
    descriptionAr: "شركة طاقة شمسية في صعيد مصر، متخصصة في محطات الطاقة الشمسية والأنظمة المتصلة بالشبكة.",
    descriptionEn: "Solar energy company in Upper Egypt, specializing in solar power stations and grid-connected systems.",
    featured: false,
    hidden: false,
  },
  {
    nameAr: "الفجر لخدمات الطاقة",
    nameEn: "Al-Fajr for Energy Services",
    sourceCategory: "up_to_50kw",
    publicCategory: "up_to_500kw",
    stationsCount: 16,
    installedPowerKw: 184.44,
    installedPowerDisplay: "184 kW",
    phone: "+20 100 307 0777",
    email: "ahmedosmanmousa@gmail.com",
    website: "",
    facebookUrl: "",
    location: "Egypt",
    descriptionAr: "شركة معتمدة لخدمات الطاقة الشمسية في مصر.",
    descriptionEn: "Certified solar energy services company in Egypt.",
    featured: false,
    hidden: false,
  },
  {
    nameAr: "آيري للطاقة المتجددة",
    nameEn: "IAREEE – International Association for Renewable Energy & Energy Efficiency",
    sourceCategory: "up_to_50kw",
    publicCategory: "up_to_500kw",
    stationsCount: 24,
    installedPowerKw: 206.34,
    installedPowerDisplay: "206 kW",
    phone: "+20 106 383 0202",
    email: "info@iareee.com",
    website: "https://iareee.com",
    facebookUrl: "https://www.facebook.com/iareee.egypt",
    location: "Heliopolis, Cairo",
    descriptionAr: "شركة متخصصة في تركيب محطات الطاقة الشمسية للمباني السكنية والتجارية. تأسست 2014 بعد برنامج نقل معرفة مع ألمانيا. تقدم ضمانات تصل إلى 25 سنة.",
    descriptionEn: "Specialist in solar installations for residential and commercial buildings. Founded 2014 after a knowledge-transfer program with Germany. Offers up to 25-year warranties.",
    featured: true,
    hidden: false,
  },
  {
    nameAr: "ايجيليك للانظمة الكهربية",
    nameEn: "Egyelec Electric Systems",
    sourceCategory: "up_to_50kw",
    publicCategory: "up_to_500kw",
    stationsCount: 1,
    installedPowerKw: 10.00,
    installedPowerDisplay: "10 kW",
    phone: "+20 100 118 8875",
    email: "maged.fouad@egyelec.com",
    website: "http://egyelec.com",
    facebookUrl: "https://www.facebook.com/EgyelecElectricSystems/",
    location: "Cairo",
    descriptionAr: "تقدم حلول الطاقة الشمسية وأنظمة الطاقة الاحتياطية وأنظمة UPS وإنفيرترات للمباني السكنية والتجارية.",
    descriptionEn: "Provides solar energy solutions, standby power systems, UPS, and inverters for residential and commercial buildings.",
    featured: false,
    hidden: false,
  },
  {
    nameAr: "مطروح للكهرباء والطاقة المتجددة",
    nameEn: "MERE – Matrouh for Electricity and Renewable Energy",
    sourceCategory: "up_to_50kw",
    publicCategory: "up_to_500kw",
    stationsCount: 2,
    installedPowerKw: 69.99,
    installedPowerDisplay: "70 kW",
    phone: "+20 101 822 2354",
    email: "sunrisematrouh2@gmail.com",
    website: "",
    facebookUrl: "https://www.facebook.com/sunrisematrouh/",
    location: "Marsa Matrouh",
    descriptionAr: "شركة متخصصة في حلول الطاقة الشمسية في محافظة مطروح والساحل الشمالي.",
    descriptionEn: "Specialist in solar energy solutions in Matrouh governorate and the North Coast.",
    featured: false,
    hidden: false,
  },
  {
    nameAr: "اي سيل لانظمة الطاقة الشمسية",
    nameEn: "iCell for Energy Systems",
    sourceCategory: "up_to_50kw",
    publicCategory: "up_to_500kw",
    stationsCount: 8,
    installedPowerKw: 79.77,
    installedPowerDisplay: "80 kW",
    phone: "+20 101 151 9526",
    email: "icell.systems@gmail.com",
    website: "",
    facebookUrl: "",
    location: "Cairo",
    descriptionAr: "شركة مصرية لأنظمة الطاقة الشمسية.",
    descriptionEn: "Egyptian solar energy systems company.",
    featured: false,
    hidden: false,
  },
  {
    nameAr: "المتحدة للصناعات الهندسية",
    nameEn: "Al-Mutahida for Contracting and Engineering Industries",
    sourceCategory: "up_to_50kw",
    publicCategory: "up_to_500kw",
    stationsCount: 1,
    installedPowerKw: 49.99,
    installedPowerDisplay: "50 kW",
    phone: "+20 100 893 3055",
    email: "almutahida0@gmail.com",
    website: "",
    facebookUrl: "https://www.facebook.com/Almotahida.Solar",
    location: "10th of Ramadan City",
    descriptionAr: "شركة متخصصة في تركيب أنظمة الطاقة الشمسية وتصنيع الهياكل المعدنية للألواح الشمسية.",
    descriptionEn: "Specializes in solar system installation and manufacturing metal frames for solar panels.",
    featured: false,
    hidden: false,
  },
  {
    nameAr: "سولار تك فاليي",
    nameEn: "Solar Tec Valley",
    sourceCategory: "up_to_50kw",
    publicCategory: "up_to_500kw",
    stationsCount: 5,
    installedPowerKw: 64.69,
    installedPowerDisplay: "65 kW",
    phone: "+20 111 477 4484",
    email: "mostafa.ibrahim@solartecvalley.com",
    website: "http://www.solartecvalley.com",
    facebookUrl: "https://www.facebook.com/STV.solartecvalley/",
    location: "New Cairo, Cairo",
    descriptionAr: "شركة طاقة شمسية تأسست عام 2015، متخصصة في تصميم وتركيب وصيانة أنظمة الطاقة الشمسية للمباني السكنية والتجارية.",
    descriptionEn: "Solar energy company founded in 2015, specializing in design, installation, and maintenance of solar systems for residential and commercial clients.",
    featured: false,
    hidden: false,
  },
  {
    nameAr: "ايفر جرين سولار",
    nameEn: "Evergreen Solar",
    sourceCategory: "up_to_50kw",
    publicCategory: "up_to_500kw",
    stationsCount: 2,
    installedPowerKw: 18.22,
    installedPowerDisplay: "18 kW",
    phone: "+20 100 850 8504",
    email: "evergreensolareg@gmail.com",
    website: "https://evergreensolareg.com",
    facebookUrl: "https://www.facebook.com/evergreensolareg/",
    location: "Obour City, Qalyubia",
    descriptionAr: "شركة متخصصة في تصنيع وتوزيع وتركيب حلول الطاقة البديلة والشمسية. تأسست 2009، نفذت أكثر من 3000 مشروع في مصر.",
    descriptionEn: "Specializes in manufacturing, distributing, and installing solar and alternative energy solutions. Founded 2009 with over 3,000 projects across Egypt.",
    featured: false,
    hidden: false,
  },
  {
    nameAr: "الشروق سمارت بلدنج",
    nameEn: "El Sherouk Smart Building",
    sourceCategory: "up_to_50kw",
    publicCategory: "up_to_500kw",
    stationsCount: 2,
    installedPowerKw: 34.20,
    installedPowerDisplay: "34 kW",
    phone: "+20 100 660 0540",
    email: "info@elsheroukco.com",
    website: "https://elsheroukco.com",
    facebookUrl: "",
    location: "Nasr City, Cairo",
    descriptionAr: "شركة متخصصة في حلول المباني الذكية ومحطات الطاقة الشمسية، تقدم مشاريع متكاملة بالكامل للمباني السكنية والزراعية والتجارية والصناعية.",
    descriptionEn: "Specializes in smart building solutions and solar power plant installation, providing turnkey projects for residential, agricultural, commercial, and industrial clients.",
    featured: false,
    hidden: false,
  },
  {
    nameAr: "وي كونستراكت",
    nameEn: "We Construct",
    sourceCategory: "up_to_50kw",
    publicCategory: "up_to_500kw",
    stationsCount: 12,
    installedPowerKw: 285.92,
    installedPowerDisplay: "286 kW",
    phone: "+20 122 818 9511",
    email: "Gamalmakram886@gmail.com",
    website: "",
    facebookUrl: "https://www.facebook.com/p/We-solar-للطاقة-الشمسية-100063482997057/",
    location: "Egypt",
    descriptionAr: "شركة معتمدة من وزارة الكهرباء وهيئة الطاقة الجديدة والمتجددة، تقدم خدمات تصميم وتوريد وتركيب مشاريع الطاقة الشمسية.",
    descriptionEn: "Certified by Egypt's Ministry of Electricity and NREA, providing solar project design, supply, and installation services.",
    featured: false,
    hidden: false,
  },
  {
    nameAr: "الهندسية للمشروعات الإلكترونية – ايبيكو",
    nameEn: "EPECO – Engineering Projects for Electronics",
    sourceCategory: "up_to_50kw",
    publicCategory: "up_to_500kw",
    stationsCount: 18,
    installedPowerKw: 154.99,
    installedPowerDisplay: "155 kW",
    phone: "+20 2 38506802",
    email: "epeco@link.net",
    website: "",
    facebookUrl: "",
    location: "6th of October City, Giza",
    descriptionAr: "شركة معتمدة من هيئة الطاقة الجديدة والمتجددة منذ 9 سنوات. تمتلك مصنعاً لإنتاج هياكل الألومنيوم المعتمدة التي تورّدها لمعظم شركات الطاقة الشمسية في مصر.",
    descriptionEn: "Accredited by NREA for 9 years. Owns a factory producing certified aluminum frames supplied to most solar companies in Egypt.",
    featured: false,
    hidden: false,
  },
  {
    nameAr: "ساميت لإدارة المشروعات والطاقة الشمسية",
    nameEn: "Summit Project Management and Solar Energy",
    sourceCategory: "up_to_50kw",
    publicCategory: "up_to_500kw",
    stationsCount: 3,
    installedPowerKw: 471.31,
    installedPowerDisplay: "471 kW",
    phone: "+20 102 107 4520",
    email: "info@summitegy.com",
    website: "https://summitegy.com",
    facebookUrl: "https://www.facebook.com/summitegy",
    location: "Cairo",
    descriptionAr: "شركة EPC متخصصة في مشاريع الطاقة الشمسية الكهروضوئية، وإدارة الإنشاء للمشاريع التجارية والسكنية.",
    descriptionEn: "EPC specialist for solar PV projects and construction management for commercial and residential developments.",
    featured: false,
    hidden: false,
  },
  {
    nameAr: "القاهرة العالمية للكمبيوتر والاتصالات والاستشارات",
    nameEn: "ICCC Cairo S.A.E.",
    sourceCategory: "up_to_50kw",
    publicCategory: "up_to_500kw",
    stationsCount: 7,
    installedPowerKw: 96.00,
    installedPowerDisplay: "96 kW",
    phone: "+20 122 215 0070",
    email: "ibrahim@iccc-cairo.com",
    website: "http://www.iccc-cairo.com",
    facebookUrl: "",
    location: "6th of October City",
    descriptionAr: "شركة تأسست عام 1995، تقدم أنظمة طاقة شمسية متصلة بالشبكة ومستقلة وهجينة تصل حتى 500 كيلوواط، فضلاً عن معدات الشبكات.",
    descriptionEn: "Founded 1995. Provides on-grid, off-grid, and hybrid solar systems up to 500 kW, plus data networking solutions.",
    featured: false,
    hidden: false,
  },

  // =================== MORE THAN 500 KW (public bucket) ===================
  {
    nameAr: "ار جي سوليوشنز",
    nameEn: "RG Solutions Egypt (RGS)",
    sourceCategory: "up_to_3mw",
    publicCategory: "above_500kw",
    stationsCount: 4,
    installedPowerKw: 72.00,
    installedPowerDisplay: "72 kW",
    phone: "+20 111 164 5485",
    email: "info@rgs-eg.com",
    website: "https://rgs-eg.com",
    facebookUrl: "https://www.facebook.com/RGS-1056506644557674/",
    location: "Obour City, Cairo",
    descriptionAr: "شركة معتمدة من هيئة الطاقة الجديدة والمتجددة، متخصصة في أنظمة الطاقة الشمسية المتصلة بالشبكة والمستقلة والهجينة وضخ المياه بالطاقة الشمسية.",
    descriptionEn: "NREA-certified company specializing in on-grid, off-grid, hybrid solar systems and solar water pumping.",
    featured: false,
    hidden: false,
  },
  {
    nameAr: "باور جرين للطاقة المستدامة",
    nameEn: "Power Green for Sustainable Energy",
    sourceCategory: "up_to_3mw",
    publicCategory: "above_500kw",
    stationsCount: 5,
    installedPowerKw: 992.55,
    installedPowerDisplay: "993 kW",
    phone: "+20 122 512 7744",
    email: "belal@powergreen.com",
    website: "https://powergreen.com",
    facebookUrl: "",
    location: "Cairo",
    descriptionAr: "شركة طاقة شمسية قائمة في مصر وقطر، تنفذ مشاريع الطاقة الشمسية الكهروضوئية للقطاع التجاري والصناعي.",
    descriptionEn: "Solar energy company operating in Egypt and Qatar, executing commercial and industrial PV projects.",
    featured: false,
    hidden: false,
  },
  {
    nameAr: "كرنا للطاقة",
    nameEn: "Karna Energy",
    sourceCategory: "up_to_3mw",
    publicCategory: "above_500kw",
    stationsCount: 2,
    installedPowerKw: 16.16,
    installedPowerDisplay: "16 kW",
    phone: "+20 122 973 1845",
    email: "info@karna-energy.com",
    website: "",
    facebookUrl: "",
    location: "Tagamoa, Cairo",
    descriptionAr: "شركة مصرية صغيرة لحلول الطاقة الشمسية.",
    descriptionEn: "Egyptian solar energy solutions company.",
    featured: false,
    hidden: false,
  },
  {
    nameAr: "صن سيتي اليكتريك لأنظمة الطاقة",
    nameEn: "Sun City Electric",
    sourceCategory: "up_to_3mw",
    publicCategory: "above_500kw",
    stationsCount: 9,
    installedPowerKw: 792.30,
    installedPowerDisplay: "792 kW",
    phone: "+20 122 888 3435",
    email: "tahaeltaher@gmail.com",
    website: "https://suncity-eg.com",
    facebookUrl: "",
    location: "New Cairo, Cairo",
    descriptionAr: "عضو ذهبي في هيئة الطاقة الجديدة والمتجددة. تقدم خدمات الطاقة الشمسية للمباني السكنية والتجارية والمدارس.",
    descriptionEn: "NREA Gold Member. Provides solar energy services for residential, commercial, and educational buildings.",
    featured: true,
    hidden: false,
  },
  {
    nameAr: "صن باور للطاقة الشمسية",
    nameEn: "Sun Power for Solar Energy",
    sourceCategory: "up_to_3mw",
    publicCategory: "above_500kw",
    stationsCount: 190,
    installedPowerKw: 4070.00,
    installedPowerDisplay: "4.07 MW",
    phone: "+20 100 264 6609",
    email: "ALhaitham20132013@gmail.com",
    website: "",
    facebookUrl: "https://www.facebook.com/Sun.power.aswan",
    location: "Aswan",
    descriptionAr: "أول شركة في صعيد مصر مؤهلة من هيئة الطاقة الجديدة والمتجددة. موزع رسمي لألواح Longi. تشغيل منذ 2014 ونفذت أكثر من 20 ميجاواط في أسوان ومحيطها.",
    descriptionEn: "First company in Upper Egypt qualified by NREA. Official Longi panels distributor. Operating since 2014 with over 20 MW installed in Aswan and surroundings.",
    featured: true,
    hidden: false,
  },
  {
    nameAr: "مؤسسة حجاب",
    nameEn: "Hegab Association (HAESC)",
    sourceCategory: "up_to_3mw",
    publicCategory: "above_500kw",
    stationsCount: 3,
    installedPowerKw: 845.73,
    installedPowerDisplay: "846 kW",
    phone: "+20 106 181 9724",
    email: "hegabassociation@outlook.com",
    website: "",
    facebookUrl: "https://www.facebook.com/HAESCInternational/",
    location: "Cairo",
    descriptionAr: "مؤسسة هندسية تأسسها المستشار د. محمد مصطفى حجاب. تقسم الطاقة الشمسية خدمات واستشارات، مؤهلة من هيئة الطاقة الجديدة والمتجددة.",
    descriptionEn: "Engineering foundation by Dr. Mohamed Mustafa Hegab. Provides solar energy services and consultancy, NREA-qualified.",
    featured: false,
    hidden: false,
  },
  {
    nameAr: "صن ستول لحلول الطاقة الجديدة والمتجددة",
    nameEn: "Sunstall",
    sourceCategory: "up_to_3mw",
    publicCategory: "above_500kw",
    stationsCount: 3,
    installedPowerKw: 142.25,
    installedPowerDisplay: "142 kW",
    phone: "+20 155 880 4730",
    email: "info@sun-stall.com",
    website: "https://sun-stall.com",
    facebookUrl: "",
    location: "El Mokattam, Cairo",
    descriptionAr: "شركة طاقة شمسية متخصصة تأسست عام 2020، تقدم خدمات التركيب وأنظمة الكهروضوئية وضخ المياه والتسخين.",
    descriptionEn: "Specialist solar company founded in 2020, providing installation services, PV systems, water pumping, and heating.",
    featured: false,
    hidden: false,
  },
  {
    nameAr: "شركة سولير لحلول توليد الطاقة",
    nameEn: "Solaire Egypt",
    sourceCategory: "up_to_3mw",
    publicCategory: "above_500kw",
    stationsCount: 71,
    installedPowerKw: 1410.00,
    installedPowerDisplay: "1.41 MW",
    phone: "+20 103 345 9890",
    email: "info@solaire-eco.com",
    website: "https://www.solaire-eco.com",
    facebookUrl: "https://www.facebook.com/Solaire.Egy/",
    location: "Dokki, Cairo",
    descriptionAr: "شركة طاقة شمسية تأسست عام 2020، تقدم حلول طاقة متجددة بأسعار معقولة للمباني السكنية والتجارية والمزارع والمصانع في مصر ومنطقة الشرق الأوسط وشمال أفريقيا.",
    descriptionEn: "Solar company founded in 2020, providing affordable renewable energy solutions for homes, businesses, farms, and factories across Egypt and MENA.",
    featured: true,
    hidden: false,
  },
  {
    nameAr: "باور كابيتال للتوريدات العمومية",
    nameEn: "Power Capital",
    sourceCategory: "up_to_3mw",
    publicCategory: "above_500kw",
    stationsCount: 4,
    installedPowerKw: 139.90,
    installedPowerDisplay: "140 kW",
    phone: "+20 109 689 9809",
    email: "info@powercapital-eg.com",
    website: "https://www.powercapital-eg.com",
    facebookUrl: "https://www.facebook.com/100063930138169/",
    location: "Fifth Settlement, Cairo",
    descriptionAr: "شركة مؤهلة من وزارة الكهرباء والطاقة المتجددة. تأسست عام 2020، تتخصص في توريد وتركيب وصيانة أنظمة الطاقة الشمسية المتكاملة.",
    descriptionEn: "Qualified by Egypt's Ministry of Electricity and Renewable Energy. Founded 2020, specializing in supply, installation, and maintenance of comprehensive solar systems.",
    featured: false,
    hidden: false,
  },
  {
    nameAr: "ايجبشن انترناشيونال سرفيسز",
    nameEn: "Egyptian International Services (EIS)",
    sourceCategory: "up_to_3mw",
    publicCategory: "above_500kw",
    stationsCount: 22,
    installedPowerKw: 580.80,
    installedPowerDisplay: "581 kW",
    phone: "+20 100 097 7901",
    email: "mohamad.aly@eis-egy.com",
    website: "http://www.eis-egy.com",
    facebookUrl: "https://www.facebook.com/EIS.Solar/",
    location: "New Maadi, Cairo",
    descriptionAr: "شركة ذهبية في قائمة هيئة الطاقة الجديدة والمتجددة. متخصصة في استيراد مكونات الطاقة الشمسية وتوريدها بالجملة وتركيب محطات شمسية حتى 500 كيلوواط.",
    descriptionEn: "NREA Golden List company. Specializes in solar component imports, wholesale, and solar station installation up to 500 kWp.",
    featured: false,
    hidden: false,
  },
  {
    nameAr: "أوچات للتشييد والطاقة المتجددة",
    nameEn: "Ojat for Construction and Renewable Energy",
    sourceCategory: "up_to_3mw",
    publicCategory: "above_500kw",
    stationsCount: 1,
    installedPowerKw: 399.28,
    installedPowerDisplay: "399 kW",
    phone: "+20 120 110 1111",
    email: "info@ojateg.com",
    website: "",
    facebookUrl: "https://www.facebook.com/ojatgroup",
    location: "Cairo",
    descriptionAr: "شركة معتمدة بالتصنيف الذهبي من هيئة الطاقة الجديدة والمتجددة. تقدم حلول خضراء متكاملة في مجال التشييد والطاقة المتجددة.",
    descriptionEn: "NREA Gold-qualified company providing integrated green solutions in construction and renewable energy.",
    featured: false,
    hidden: false,
  },
  {
    nameAr: "مشرق لانظمة الطاقة",
    nameEn: "Mashreq for Energy Systems",
    sourceCategory: "up_to_3mw",
    publicCategory: "above_500kw",
    stationsCount: 4,
    installedPowerKw: 477.00,
    installedPowerDisplay: "477 kW",
    phone: "+20 111 113 5427",
    email: "moamen.mohamed@mashreqco.com",
    website: "http://www.mashreqco.com",
    facebookUrl: "https://www.facebook.com/mashreqco",
    location: "Smart Village, Cairo",
    descriptionAr: "مقاول EPC متخصص في أنظمة الطاقة الشمسية لضخ المياه والأنظمة المتصلة بالشبكة والمستقلة للقطاع الزراعي والصناعي والتجاري. تأسست 2016.",
    descriptionEn: "EPC contractor specializing in solar water pumping, grid-tied, and off-grid systems for agricultural, industrial, and commercial sectors. Founded 2016.",
    featured: false,
    hidden: false,
  },
  {
    nameAr: "ذي سولار كومباني ايجيبت للطاقة",
    nameEn: "The Solar Company (TSC)",
    sourceCategory: "up_to_3mw",
    publicCategory: "above_500kw",
    stationsCount: 97,
    installedPowerKw: 3070.00,
    installedPowerDisplay: "3.07 MW",
    phone: "+20 122 410 2498",
    email: "info@tsc.solar",
    website: "https://www.tsc.solar",
    facebookUrl: "https://www.facebook.com/TheSolarCompanyEG",
    location: "Maadi, Cairo",
    descriptionAr: "شركة EPC معتمدة، تابعة لـ SolarizEgypt. متخصصة في تركيبات الطاقة الشمسية السكنية والتجارية والزراعية. رقم 1 في مصر لمحطات الطاقة الشمسية السكنية.",
    descriptionEn: "EPC-certified subsidiary of SolarizEgypt. Specializes in residential, commercial, and agricultural solar installations. #1 in Egypt for residential solar.",
    featured: true,
    hidden: false,
  },
  {
    nameAr: "الشركة المصرية لأنظمة الطاقة الشمسية",
    nameEn: "Egyptian Solar Energy Systems Co.",
    sourceCategory: "up_to_3mw",
    publicCategory: "above_500kw",
    stationsCount: 100,
    installedPowerKw: 7430.00,
    installedPowerDisplay: "7.43 MW",
    phone: "+20 3 5737813",
    email: "info@egyptsolar.net",
    website: "https://egyptsolar.net",
    facebookUrl: "",
    location: "6th of October City and Giza",
    descriptionAr: "شركة رائدة تأسست عام 1989. متخصصة في سخانات المياه الشمسية وأنظمة الكهروضوئية منذ 2011 وأنظمة التهوية. مصنعها في مدينة 6 أكتوبر الصناعية.",
    descriptionEn: "Pioneer company founded in 1989. Specializes in solar water heaters, PV systems since 2011, and ventilation systems. Factory in 6th of October industrial zone.",
    featured: true,
    hidden: false,
  },
  {
    nameAr: "تي ام باور",
    nameEn: "TM Power",
    sourceCategory: "up_to_3mw",
    publicCategory: "above_500kw",
    stationsCount: 6,
    installedPowerKw: 351.85,
    installedPowerDisplay: "352 kW",
    phone: "+20 128 933 7260",
    email: "startotg43@yahoo.com",
    website: "",
    facebookUrl: "https://www.facebook.com/p/TM-Power-61578879477577/",
    location: "Egypt",
    descriptionAr: "شركة طاقة شمسية مدرجة في القائمة الذهبية المصرية لمحطات الطاقة الشمسية.",
    descriptionEn: "Solar energy company listed on Egypt's golden solar energy companies list.",
    featured: false,
    hidden: false,
  },
  {
    nameAr: "سولاتك جروب للطاقة المتجددة",
    nameEn: "Solatech Group",
    sourceCategory: "up_to_3mw",
    publicCategory: "above_500kw",
    stationsCount: 11,
    installedPowerKw: 975.84,
    installedPowerDisplay: "976 kW",
    phone: "+20 120 000 6310",
    email: "info@solatechgroup.com",
    website: "https://solatechgroup.com",
    facebookUrl: "https://www.facebook.com/solatechgroup",
    location: "Heliopolis, Cairo",
    descriptionAr: "شركة مصرية تأسست عام 2016، متخصصة في حلول الطاقة المتجددة بما فيها الطاقة الشمسية وطاقة الرياح للتطبيقات السكنية والتجارية والريفية.",
    descriptionEn: "Egyptian company founded in 2016, specializing in renewable energy solutions including solar and wind for residential, commercial, and rural applications.",
    featured: false,
    hidden: false,
  },
  {
    nameAr: "تكنو باور لانظمة الطاقة الشمسية",
    nameEn: "Techno Power for Solar Energy Systems",
    sourceCategory: "up_to_3mw",
    publicCategory: "above_500kw",
    stationsCount: 1,
    installedPowerKw: 56.40,
    installedPowerDisplay: "56 kW",
    phone: "+20 103 002 4500",
    email: "techno4power@gmail.com",
    website: "",
    facebookUrl: "https://www.facebook.com/techno4power/",
    location: "Qena",
    descriptionAr: "شركة مدرجة في القائمة الذهبية لهيئة الطاقة الجديدة والمتجددة، تقوم بتوريد وتركيب وصيانة محطات الطاقة الشمسية.",
    descriptionEn: "NREA Golden List company. Supplies, installs, and maintains solar power stations.",
    featured: false,
    hidden: false,
  },
  {
    nameAr: "جيت سولار",
    nameEn: "Jet Solar",
    sourceCategory: "up_to_3mw",
    publicCategory: "above_500kw",
    stationsCount: 1,
    installedPowerKw: 499.96,
    installedPowerDisplay: "500 kW",
    phone: "+20 123 453 4333",
    email: "info@jet-solar.com",
    website: "https://www.jet-solar.com",
    facebookUrl: "https://www.facebook.com/jetsolareg/",
    location: "Abu Rawash, Giza",
    descriptionAr: "شركة مصرية رائدة تأسست عام 2020، متخصصة في تصميم وتصنيع وتركيب أنظمة الطاقة الشمسية عالية الجودة. حاصلة على شهادات TÜV وISO.",
    descriptionEn: "Leading Egyptian company founded in 2020, specializing in designing, manufacturing, and installing high-quality solar energy systems. TÜV & ISO certified.",
    featured: false,
    hidden: false,
  },
  {
    nameAr: "تيد أن خدمات الطاقه والبيئة",
    nameEn: "TedEn – The Energy and Environmental Hub",
    sourceCategory: "up_to_3mw",
    publicCategory: "above_500kw",
    stationsCount: 7,
    installedPowerKw: 1340.00,
    installedPowerDisplay: "1.34 MW",
    phone: "+20 122 629 1935",
    email: "mariamghobrial138@gmail.com",
    website: "https://tedenhub.com",
    facebookUrl: "",
    location: "Heliopolis, Cairo",
    descriptionAr: "شركة ESCO تأسست عام 2017، متخصصة في الطاقة الشمسية وكفاءة الطاقة وأنظمة إدارة الطاقة. تقدم حلولاً متكاملة للطاقة الشمسية وتشغيل أنظمة هجينة شمسية-ديزل.",
    descriptionEn: "ESCO founded in 2017, specializing in solar power, energy efficiency, and energy management systems. Delivers turnkey solar solutions and hybrid solar-diesel systems.",
    featured: false,
    hidden: false,
  },
  {
    nameAr: "بيور باور",
    nameEn: "Pure Power",
    sourceCategory: "up_to_3mw",
    publicCategory: "above_500kw",
    stationsCount: 34,
    installedPowerKw: 1580.00,
    installedPowerDisplay: "1.58 MW",
    phone: "+20 122 717 3560",
    email: "refaat.gaabour@purepower-egypt.com",
    website: "https://purepower-egypt.com",
    facebookUrl: "https://www.facebook.com/purepower.egypt",
    location: "Fifth Settlement, Cairo",
    descriptionAr: "شركة تأسست عام 2014، تمتد خبرتها لأكثر من 10 سنوات في مجال الطاقة الشمسية. موزع معتمد لألواح JA Solar. تخدم المباني السكنية والتجارية والتعليمية.",
    descriptionEn: "Founded 2014 with over 10 years of solar expertise. Authorized JA Solar modules distributor. Serves residential, commercial, and educational buildings.",
    featured: false,
    hidden: false,
  },
  {
    nameAr: "ايريس سولار",
    nameEn: "IRIS Solar LLC.",
    sourceCategory: "up_to_3mw",
    publicCategory: "above_500kw",
    stationsCount: 3,
    installedPowerKw: 1000.00,
    installedPowerDisplay: "1.00 MW",
    phone: "+20 122 222 7344",
    email: "MSGabr@irisegypt.org",
    website: "https://www.irisegypt.org",
    facebookUrl: "",
    location: "Cairo",
    descriptionAr: "شركة متخصصة في حلول الطاقة المتجددة للمشاريع التجارية والسكنية. من أبرز مشاريعها: محطة شمسية 5.25 ميجاواط لشركة لوتس تكس، أكبر سطح صناعي في مصر.",
    descriptionEn: "Specializes in renewable energy for commercial and residential projects. Notable project: 5.25 MW rooftop for Lotus Tex, the largest industrial rooftop solar in Egypt.",
    featured: false,
    hidden: false,
  },
  {
    nameAr: "مدينة نصر للتجارة",
    nameEn: "Nasr City Solar",
    sourceCategory: "up_to_3mw",
    publicCategory: "above_500kw",
    stationsCount: 35,
    installedPowerKw: 4830.00,
    installedPowerDisplay: "4.83 MW",
    phone: "+20 101 540 0784",
    email: "hossam@nasrcitysolar.com",
    website: "https://www.nasrcitysolar.com",
    facebookUrl: "",
    location: "Nasr City, Cairo",
    descriptionAr: "شركة ذهبية المرخصة تعمل منذ 2016. تقدم أنظمة الطاقة الشمسية المتصلة بالشبكة والمستقلة وضخ المياه وخدمات الصيانة.",
    descriptionEn: "Gold-licensed company operating since 2016. Provides on/off-grid solar systems, irrigation, and maintenance services.",
    featured: false,
    hidden: false,
  },
  {
    nameAr: "ايكو لحلول المياه و الطاقة الشمسية",
    nameEn: "Eco Solutions",
    sourceCategory: "up_to_3mw",
    publicCategory: "above_500kw",
    stationsCount: 23,
    installedPowerKw: 2830.00,
    installedPowerDisplay: "2.83 MW",
    phone: "+20 106 333 5488",
    email: "info@ecosolutioneg.com",
    website: "https://ecosolutioneg.com",
    facebookUrl: "",
    location: "Hurghada",
    descriptionAr: "شركة تأسست عام 2018 في الغردقة. أول شركة في محافظة البحر الأحمر لحلول الطاقة الشمسية ومعالجة المياه. تقدم أيضاً محطات تحلية المياه وأنظمة الري الشمسي.",
    descriptionEn: "Founded in Hurghada in 2018. First company in the Red Sea governorate for solar energy and water treatment. Also provides desalination and solar irrigation systems.",
    featured: false,
    hidden: false,
  },
  {
    nameAr: "رابتور للتوريدات الهندسية والمقاولات",
    nameEn: "Raptor Engineering Supplies & Contracting (R.E.S.C)",
    sourceCategory: "up_to_3mw",
    publicCategory: "above_500kw",
    stationsCount: 75,
    installedPowerKw: 2340.00,
    installedPowerDisplay: "2.34 MW",
    phone: "+20 122 770 4942",
    email: "atefsanad@raptor-es.com",
    website: "https://raptor-es.com",
    facebookUrl: "https://www.facebook.com/RaptorSolar/",
    location: "Tanta",
    descriptionAr: "شركة تعمل منذ 2015، متخصصة في أنظمة ضخ المياه بالطاقة الشمسية والأنظمة المستقلة والمتصلة بالشبكة والري الحديث. مدرجة في القائمة الذهبية لهيئة الطاقة المتجددة.",
    descriptionEn: "Operating since 2015. Specializes in solar pump systems, off/on-grid solar, and modern irrigation. Listed on NREA golden list.",
    featured: false,
    hidden: false,
  },
  {
    nameAr: "إيكوتك للأعمال والتجارة",
    nameEn: "Eco-Tech for Renewable Energy and Automation",
    sourceCategory: "up_to_3mw",
    publicCategory: "above_500kw",
    stationsCount: 41,
    installedPowerKw: 2000.00,
    installedPowerDisplay: "2.00 MW",
    phone: "+20 100 503 9485",
    email: "marwa.elnady@ecotecheg.com",
    website: "",
    facebookUrl: "",
    location: "Gesr Al-Suez, Cairo",
    descriptionAr: "شركة متخصصة في حلول الطاقة المتجددة بما فيها الألواح الشمسية وسخانات المياه وضخ المياه وأنظمة الكهرباء الاحتياطية والتدريب.",
    descriptionEn: "Specializes in renewable energy solutions including solar panels, water heating, water pumping, backup power systems, and training.",
    featured: false,
    hidden: false,
  },
  {
    nameAr: "اونيرا لأنظمة الطاقة",
    nameEn: "OneraSystems",
    sourceCategory: "up_to_3mw",
    publicCategory: "above_500kw",
    stationsCount: 23,
    installedPowerKw: 2290.00,
    installedPowerDisplay: "2.29 MW",
    phone: "+20 100 007 0284",
    email: "info@onerasystems.com",
    website: "https://www.onerasystems.com",
    facebookUrl: "https://www.facebook.com/OneraSystems",
    location: "Cairo-Alexandria Desert Road, Giza",
    descriptionAr: "شركة تابعة لـ MEET Egypt، متخصصة في الأنظمة الشمسية النظيفة والفعّالة لقطاعات الاتصالات والنفط والغاز والمرافق وغيرها.",
    descriptionEn: "Subsidiary of MEET Egypt, specializing in clean and efficient solar systems for telecom, oil & gas, utilities, and other sectors.",
    featured: false,
    hidden: false,
  },
  {
    nameAr: "تومورو سولار",
    nameEn: "Tomorrow Solar",
    sourceCategory: "up_to_3mw",
    publicCategory: "above_500kw",
    stationsCount: 28,
    installedPowerKw: 1290.00,
    installedPowerDisplay: "1.29 MW",
    phone: "+20 100 064 6331",
    email: "info@tomorrowsolar.com.eg",
    website: "https://tomorrowsolar.com.eg",
    facebookUrl: "https://www.facebook.com/tomorrow30",
    location: "Al Shorouk City, Cairo",
    descriptionAr: "شركة متخصصة في حلول الطاقة المتجددة: الطاقة الشمسية الكهروضوئية وسخانات المياه الشمسية وشحن السيارات الكهربائية والتطوير والاستثمار ومشاريع EPC.",
    descriptionEn: "Specializes in renewable energy solutions: PV solar, solar water heating, EV charging, development, investment, and EPC projects.",
    featured: false,
    hidden: false,
  },
  {
    nameAr: "سولاريس للحلول المبتكرة",
    nameEn: "Solaris Innovative Solutions",
    sourceCategory: "up_to_3mw",
    publicCategory: "above_500kw",
    stationsCount: 10,
    installedPowerKw: 197.19,
    installedPowerDisplay: "197 kW",
    phone: "+20 122 210 6087",
    email: "info@solaris-eg.com",
    website: "https://solaris-eg.com",
    facebookUrl: "https://www.facebook.com/solarenergysolaris/",
    location: "Mohandessin, Giza",
    descriptionAr: "شركة تأسست عام 2009، تقدم حلولاً بيئية مبتكرة بما فيها التسخين الشمسي الحراري وأنظمة الكهروضوئية وأنظمة الإضاءة الطبيعية بالأنابيب الشمسية.",
    descriptionEn: "Founded in 2009, providing innovative eco-friendly solutions including solar thermal heating, PV systems, and tubular solar daylighting.",
    featured: false,
    hidden: false,
  },
  {
    nameAr: "تسلا باور ايجيبت",
    nameEn: "Tesla Power Egypt",
    sourceCategory: "up_to_3mw",
    publicCategory: "above_500kw",
    stationsCount: 1,
    installedPowerKw: 200.40,
    installedPowerDisplay: "200 kW",
    phone: "+20 103 333 9002",
    email: "info@tesla-egypt.com",
    website: "",
    facebookUrl: "https://www.facebook.com/teslapoweregypt",
    location: "Giza",
    descriptionAr: "شركة مصرية متخصصة في توريد وتركيب وتصميم وتنفيذ أنظمة الطاقة الشمسية الكهروضوئية وضخ المياه بالطاقة الشمسية وسخانات المياه الشمسية.",
    descriptionEn: "Egyptian company specializing in supply, installation, design, and execution of PV solar systems, solar water pumping, and solar water heating.",
    featured: false,
    hidden: false,
  },
  {
    nameAr: "المصرية لمشروعات الطاقة والتبريد – جاس كول",
    nameEn: "Gascool – Egyptian Company for Energy and Cooling Projects",
    sourceCategory: "up_to_3mw",
    publicCategory: "above_500kw",
    stationsCount: 5,
    installedPowerKw: 304.64,
    installedPowerDisplay: "305 kW",
    phone: "+20 2 23292720",
    email: "ceo@gascool-eg.com",
    website: "https://www.gascool-eg.com",
    facebookUrl: "https://www.facebook.com/gascool_official",
    location: "Nasr City, Cairo",
    descriptionAr: "شركة حكومية مصرية مئة بالمئة تأسست عام 2004، رائدة في مجال التبريد والتدفئة المركزية. تنفذ مشاريع طاقة شمسية لمباني القطاع البترولي المصري.",
    descriptionEn: "100% government-owned company founded in 2004, pioneer in district cooling and heating. Executes solar projects for Egyptian petroleum sector buildings.",
    featured: false,
    hidden: false,
  },
  {
    nameAr: "بدائل للطاقة الشمسية والاستيراد والتصدير",
    nameEn: "Badael Solar Energy",
    sourceCategory: "up_to_3mw",
    publicCategory: "above_500kw",
    stationsCount: 39,
    installedPowerKw: 4140.00,
    installedPowerDisplay: "4.14 MW",
    phone: "+20 122 494 3948",
    email: "bdael.solar.power@gmail.com",
    website: "https://bdael.com",
    facebookUrl: "https://www.facebook.com/b.solar.p/",
    location: "Tanta, Gharbia",
    descriptionAr: "أول شركة طاقة شمسية في طنطا، تأسست عام 2014. متخصصة في تصميم وتوريد وتركيب أنظمة الطاقة الشمسية المتصلة بالشبكة والمستقلة وضخ المياه.",
    descriptionEn: "First solar company in Tanta, founded 2014. Specializes in design, supply, and installation of grid-tied, off-grid solar systems and water pumping.",
    featured: false,
    hidden: false,
  },
  {
    nameAr: "الأفضل للطاقة الشمسية",
    nameEn: "Al Afdal Solar Energy",
    sourceCategory: "up_to_3mw",
    publicCategory: "above_500kw",
    stationsCount: 12,
    installedPowerKw: 137.24,
    installedPowerDisplay: "137 kW",
    phone: "+20 100 040 8483",
    email: "bestsolar787@gmail.com",
    website: "",
    facebookUrl: "https://www.facebook.com/bestsolar.Group/",
    location: "Cairo",
    descriptionAr: "شركة مصرية لمنتجات الطاقة الشمسية والخدمات الزراعية، تشارك في معارض الطاقة الشمسية في مصر.",
    descriptionEn: "Egyptian company dealing in solar energy products and agricultural services, participating in solar exhibitions across Egypt.",
    featured: false,
    hidden: false,
  },
  {
    nameAr: "العالمية لأنظمة الطاقة المتجددة",
    nameEn: "Elalamiah for Renewable Energy Systems",
    sourceCategory: "up_to_3mw",
    publicCategory: "above_500kw",
    stationsCount: 20,
    installedPowerKw: 1480.00,
    installedPowerDisplay: "1.48 MW",
    phone: "+20 109 186 7272",
    email: "sherif_imam@hotmail.com",
    website: "",
    facebookUrl: "https://www.facebook.com/alalamiah/",
    location: "Sidi Bishr, Alexandria",
    descriptionAr: "شركة موردة ومصنّعة ومنفذة لأنظمة الطاقة الشمسية المتصلة بالشبكة والمستقلة والهجينة وضخ المياه وسخانات المياه.",
    descriptionEn: "Solar systems supplier, manufacturer, and installer: on-grid, off-grid, hybrid, pumping, and solar water heaters.",
    featured: false,
    hidden: false,
  },
  {
    nameAr: "الرؤية المتقدمة للتنمية",
    nameEn: "Advanced Vision Egypt (AVE)",
    sourceCategory: "up_to_3mw",
    publicCategory: "above_500kw",
    stationsCount: 1,
    installedPowerKw: 405.00,
    installedPowerDisplay: "405 kW",
    phone: "+20 100 840 0044",
    email: "Mohamed.nasser@adv-vision.co",
    website: "https://www.avegypt.com",
    facebookUrl: "",
    location: "Badr City",
    descriptionAr: "شركة مساهمة مصرية متخصصة في خدمات الميكانيكا والكهرباء والسباكة والبنية التحتية وحلول الطاقة المتجددة.",
    descriptionEn: "Egyptian joint stock company specializing in MEP, infrastructure, and renewable energy solutions.",
    featured: false,
    hidden: false,
  },
  {
    nameAr: "بنها للصناعات الإلكترونية",
    nameEn: "Benha Electronics Industries",
    sourceCategory: "up_to_3mw",
    publicCategory: "above_500kw",
    stationsCount: 51,
    installedPowerKw: 3390.00,
    installedPowerDisplay: "3.39 MW",
    phone: "+20 113 322 4237",
    email: "ben_hq@katron.com.eg",
    website: "https://fact144.momp.gov.eg",
    facebookUrl: "https://www.facebook.com/61571270642525",
    location: "Benha, Qalyubia",
    descriptionAr: "شركة حكومية تابعة لوزارة الإنتاج الحربي. رائدة في الصناعات الإلكترونية منذ الستينيات. تمتلك مصنعاً للألواح الشمسية بطاقة 50 ميجاواط سنوياً.",
    descriptionEn: "State-owned company under Egypt's Ministry of Military Production. Pioneer in electronic industries since the 1960s. Owns a solar panel factory with 50 MW annual capacity.",
    featured: false,
    hidden: false,
  },
  {
    nameAr: "الشركة الهندسية لخدمات الطاقة الشمسية – ESSE",
    nameEn: "ESSE – Engineering Company for Solar Energy Services",
    sourceCategory: "up_to_3mw",
    publicCategory: "above_500kw",
    stationsCount: 2,
    installedPowerKw: 549.00,
    installedPowerDisplay: "549 kW",
    phone: "+20 122 274 8117",
    email: "amirosman2020@yahoo.com",
    website: "",
    facebookUrl: "https://www.facebook.com/ESSEC.solar/",
    location: "Cairo",
    descriptionAr: "شركة مدرجة في القائمة الذهبية لهيئة الطاقة الجديدة والمتجددة (كود 67). تقدم خدمات التصميم والتنفيذ والدراسات التقنية والمالية والصيانة لمشاريع الطاقة الشمسية.",
    descriptionEn: "NREA Gold List company (code 67). Provides solar project design, execution, technical and financial studies, and maintenance.",
    featured: false,
    hidden: false,
  },
  {
    nameAr: "اندروميدا لاعمال الطاقة الشمسية",
    nameEn: "Andromeda Egypt",
    sourceCategory: "up_to_3mw",
    publicCategory: "above_500kw",
    stationsCount: 1,
    installedPowerKw: 20.00,
    installedPowerDisplay: "20 kW",
    phone: "+20 100 141 7225",
    email: "lara.elkalamawy@karmsolar.com",
    website: "",
    facebookUrl: "",
    location: "Egypt",
    descriptionAr: "شركة مصرية لأعمال الطاقة الشمسية.",
    descriptionEn: "Egyptian solar energy works company.",
    featured: false,
    hidden: false,
  },
  {
    nameAr: "مكتب أوروبا للمقاولات الكهروميكانيكية",
    nameEn: "Europe for Contracting and Solar Energy",
    sourceCategory: "up_to_3mw",
    publicCategory: "above_500kw",
    stationsCount: 7,
    installedPowerKw: 740.00,
    installedPowerDisplay: "740 kW",
    phone: "+20 100 040 6544",
    email: "energyengineer@europesolar.org",
    website: "https://www.europesolar.org/en",
    facebookUrl: "https://www.facebook.com/europelifts",
    location: "Farafra, New Valley",
    descriptionAr: "شركة متخصصة في توريد وتركيب الطاقة الشمسية والمقاولات الكهروميكانيكية واستصلاح الأراضي الصحراوية. نفذت أكثر من 1200 مشروع شمسي.",
    descriptionEn: "Specializes in solar energy supply, installation, electromechanical contracting, and desert land reclamation. Implemented over 1,200 solar projects.",
    featured: false,
    hidden: false,
  },
  {
    nameAr: "الكرم لبيع وتوزيع الكهرباء",
    nameEn: "KarmSolar – Al-Karm for Sale and Distribution of Electricity",
    sourceCategory: "up_to_3mw",
    publicCategory: "above_500kw",
    stationsCount: 28,
    installedPowerKw: 40610.00,
    installedPowerDisplay: "40.61 MW",
    phone: "+20 2 27360429",
    email: "samiha.elansary@karmsolar.com",
    website: "https://www.karmholding.com",
    facebookUrl: "https://www.facebook.com/KarmSolar",
    location: "Zamalek, Cairo",
    descriptionAr: "شركة الطاقة الشمسية الخاصة الرائدة في مصر. متخصصة في توليد الطاقة الشمسية وشبكات توزيع الكهرباء الخاصة. سعة تعاقدية تتجاوز 195 ميجافولت أمبير. مرخصة من هيئة تنظيم مرفق الكهرباء.",
    descriptionEn: "Egypt's leading private solar utility. Specializes in solar power generation and private electricity distribution networks. Over 195 MVA contracted capacity. Licensed by EGYPTERA.",
    featured: true,
    hidden: false,
  },
];

export async function seed() {
  const existing = db.select().from(installers).all();
  if (existing.length > 0) {
    console.log("Database already seeded, skipping.");
    return;
  }
  for (const item of seedData) {
    db.insert(installers).values(item).run();
  }
  console.log(`Seeded ${seedData.length} installers.`);
}
